---
- name: Restore iptables settings
  hosts: ng
  tasks:
    - name: Copy iptables rules file
      copy:
        src: /home/alex/ansible/balancer/iptables.rules
        dest: /root
        mode: 0644
    - name: Run iptables-restore command
      shell: iptables-restore < /root/iptables.rules
    - name: Disable Password Authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
      notify:
       - restart sshd
    - name: Install iptables-persistent
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - iptables-persistent
        - netfilter-persistent
  
  handlers:
   - name: restart sshd
     systemd:
       name: sshd
       state: restarted
